### ISSUE TITLE
FEATURE REQUEST 

### ISSUE THREAD

**Issue by Choneke** [fidelity/seq2pat#23]
I would like to thank for this work, and is very helpful.

I have a request/question concerning about output generation. Currently, the sequences/output are generated with their support(count) at the right hand side, eg [ ['A', 'B', 3], ['C', 'D', 'A' 6]], whereby 6 and 3 represent support (count) of generated sequence respectively. 

Is there a means of generating that support(count) in terms of %? instead of raw integer? 

Or the best option will be if the entered support is in %, then the output support should be in %. Also if if the entered support is in raw integer then the output support should be in raw integer.

Thank you.

**Comment by takojunior** [comment]
Thanks @Choneke for your interests! Notice that the issue is just closed. Sorry for the late reply but I just would like to share my thinking on this.

Regarding your question, I think the easiest way to get the support in % for now would still be a post processing step, given that we know the total number of sequences.

Besides, another thought around not returning % would be that it might be a little nonintuitive to distinguish the support of two patterns with similar frequency. In that case, we might need to choose how many decimal places to keep in the returns, e.g. 9.9% vs 9.92%, then using one decimal place makes the two to be the same.

So hopefully transforming the integer support to % would be an easy thing to do and it won't be a blocker to solve the problem.
