### ISSUE TITLE
【QUESTION】Any way to limit the minimum length of each pattern?

### ISSUE THREAD

**Issue by Wwwwei** [fidelity/seq2pat#28]
Thanks for this helpful work.
I wonder if there is any way to limit the minimum length of each pattern.
Referring to the Dichotomic Pattern Mining paper, I add an order attribute (the sequential order in a sequence, e.g. [A, B, C, D] has the attribute [0, 1, 2, 3]) and add a constraint 5 <= att_order.span() <= 10 to limit the length to between 5 and 10. However, I find it does not work.

Can you share how to deal with the above issue?
Thank you very much.

**Comment by takojunior** [comment]
Thanks @Wwwwei for your interests. To your question, I don't see a way by applying currently available constraints to limit the minimum length of patterns. The span constraint you used above is actually requiring MAX(att_order) - MIN(att_order) of a pattern to be within the range [5, 10], which doesn't necessarily limit the minimum length of pattern. Besides, it may not find patterns satisfying the constraint since the maximum span of pattern would be 3, that is falling outside of the specified range.

The easiest way for now would be a post-processing step. What we shall do is to get patterns without limiting the minimum length first, then we select the patterns that can pass the desired requirement. I hope this can help to solve the problem.

**Comment by Sandy4321** [comment]
yes
good question

**Comment by Wwwwei** [comment]
> 

Thanks for your prompt reply. I will try post-processing.
By the way, is there any way to speed up and reduce memory? I am suffering from high time and memory consumption in a big dataset.
Thank you very much.

**Comment by Wwwwei** [comment]
Thanks. Looking forward to the new feature.
