### ISSUE TITLE
Patterns with a single event

### ISSUE THREAD

**Issue by victorjmarin** [fidelity/seq2pat#37]
Hello there!

Single-event patterns seem to be problematic. Below are two examples depicting the issue:

```
from sequential.seq2pat import Seq2Pat

seq2pat = Seq2Pat(sequences=[["A"], ["A"], ["A"]])
seq_patterns = seq2pat.get_patterns(min_frequency=2)
print(seq_patterns)  # Outputs []. Expected [["A", 3]]

seq2pat = Seq2Pat(sequences=[["A"], ["A", "B"], ["A"], ["A", "B"]])
seq_patterns = seq2pat.get_patterns(min_frequency=2)
print(seq_patterns)  # Outputs [["A", "B", 2]]. Expected [["A", 4], ["A", "B", 2]]
```

Thank you.

**Comment by takojunior** [comment]
Thanks @victorjmarin. I see the issue. Unfortunately the library is not returning length-1 patterns. Since we consider the constraint such as GAP that uses at least two items as the mining algorithm goes, there seems not a clean solution to tackle the length-1 cases. We will add a note to documentations about this issue until we figure out a fix.

**Comment by skadio** [comment]
Agreed, I don't think this requires a fix, apart from note/document/error handling. A list of size 1 is not that interesting and does not really qualify as a "sequence".
